# Generated by Django 6.0.2 on 2026-05-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_post_comment_like_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("Event", "Event"),
                    ("Achievement", "Achievement"),
                    ("Club Activity", "Club Activity"),
                    ("Announcement", "Announcement"),
                    ("Study", "Study"),
                    ("Fun Moment", "Fun Moment"),
                ],
                default="Fun Moment",
                max_length=50,
            ),
        ),
    ]
