# Generated by Django 6.0.2 on 2026-05-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="year",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
