# Generated by Django 6.0.2 on 2026-05-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_department_profile_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("Event", "Event"),
                    ("Achievement", "Achievement"),
                    ("Club Activity", "Club Activity"),
                    ("Announcement", "Announcement"),
                    ("Study Material", "Study Material"),
                    ("Lost & Found", "Lost & Found"),
                    ("Fun Moment", "Fun Moment"),
                ],
                default="Fun Moment",
                max_length=50,
            ),
        ),
    ]
